[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"
tries = 3

[nvchecker]
source = "github"
github = "lilydjwg/nvchecker"
use_max_tag = true

[Antares]
source = "github"
github = "antares-sql/antares"
use_latest_release = true

[compose]
source = "github"
github = "docker/compose"
use_latest_release = true

[insomnia]
source = "github"
github = "Kong/insomnia"
use_latest_release = true

[gotify]
source = "github"
github = "gotify/server"
use_latest_release = true

[balena-engine]
source = "github"
github = "balena-os/balena-engine"
use_max_tag = true
