[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"
tries = 3

[nvchecker]
source = "github"
github = "lilydjwg/nvchecker"
use_max_tag = true

[Antares]
source = "github"
github = "antares-sql/antares"
use_latest_release = true
