name: nvchecker

on:
  push:
    branches:
      - master
    paths:
      - 'source.ini'
  pull_request:
    branches:
      - master
    paths:
      - 'source.ini'
  schedule:
    - cron: '0 */3 * * *'

env:
  IMAGE_NAME: nvchecker

jobs:
  check-new-versions:
    runs-on: ubuntu-latest
    name: Check New Versions

    steps:
      - uses: actions/checkout@v2

      - name: Set environment variables
        run: |
          IMAGE_ID=docker.pkg.github.com/$GITHUB_REPOSITORY/$IMAGE_NAME
          echo "::set-env name=IMAGE_ID::$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')"
          echo "::set-env name=IMAGE_TAG::$IMAGE_ID:latest"

          echo "::set-env name=LOG_FILE::nvchecker_$(date +'%Y-%m-%d_%H-%M-%S').log"

      - name: Log into registry
        # $GITHUB_ACTOR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Pull Docker image
        run: docker pull "${{ env.IMAGE_ID }}"

      - name: Run image
        run: docker run -it -d --name nvchecker-app -v $GITHUB_WORKSPACE:/workspace -w /workspace --env NVCHECKER_GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} ${{ env.IMAGE_ID }}:latest

      - name: Check version
        run: |
          # echo "::set-env name=VERSIONS_COMPARE::$(docker exec nvchecker-app nvcmp source.ini 2>&1)"

          touch old_ver.txt new_ver.txt

          docker exec nvchecker-app nvchecker --tries 3 source.ini 2>&1 | tee ${{ env.LOG_FILE }}
          docker exec nvchecker-app nvcmp source.ini > result.tmp
          docker exec nvchecker-app nvtake source.ini --all

      - name: Send Email
        run: |
          RESULT=$(cat result.tmp)
          [[ ! -z $RESULT ]] && curl -s --user 'api:${{ secrets.MAILGUN_API_KEY }}' https://api.mailgun.net/v3/${{ secrets.MAILGUN_DOMAIN_NAME }}/messages -F from='nvchecker <postmaster@${{ secrets.MAILGUN_DOMAIN_NAME }}>' -F to=${{ secrets.EMAIL_TO }} -F subject='New version check result' -F text="$RESULT" --form-string html="<html><pre><code>$RESULT</code></pre><hr /></html>" -F attachment=@${{ env.LOG_FILE }} || echo "No new versions"
          rm -f result.tmp ${{ env.LOG_FILE }}

      - name: Commit version record files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: Apply version record files changes'

          branch: ${{ github.head_ref }}
          commit_options: "--no-verify --signoff"
          file_pattern: ./*.txt
          repository: .

          commit_user_name: GitHub Actions
          commit_user_email: actions@github.com
          commit_author: GitHub Actions <actions@github.com>

      # - name: nvchecker-action
      #   id: nvchecker-action
      #   uses: guizai/nvchecker-action@master
      #   with:
      #     source-file: 'source.ini'
