name: nvchecker

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "config.toml"
      - ".github/workflows/nvchecker.yml"
  pull_request:
    branches:
      - master
    paths:
      - "config.toml"
      - ".github/workflows/nvchecker.yml"
  schedule:
    - cron: "0 */3 * * *"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  check-new-versions:
    name: Check New Versions
    runs-on: ubuntu-latest
    container:
      # image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      image: ghcr.io/bergpb/nvchecker-github-actions
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          echo "LOG_FILE=nvchecker_$(date +'%Y-%m-%d_%H-%M-%S').log" >> $GITHUB_ENV
          sed -i -e "s/__GITHUB_ACCESS_TOKEN__/${{ secrets.GH_TOKEN }}/g" keyfile.toml

      - name: Check version
        run: |
          nvchecker --file config.toml --keyfile keyfile.toml 2>&1 | tee ${{ env.LOG_FILE }}
          nvcmp --file config.toml > result.tmp
          nvtake --file config.toml --all

      - name: Send Gotify Notification
        shell: bash
        run: |
          LOG=$(cat ${{ env.LOG_FILE }}) \
          RESULT=$(cat result.tmp) \
          DATE=$(date +"%Y-%m-%d") \
          TITLE="nvchecker Updates"
          PRIORITY=5
          URL="${{ secrets.GOTIFY_SERVER }}/message?token=${{ secrets.GOTIFY_TOKEN }}"
          && [[ ! -z $LOG ]] || [[ ! -z $RESULT ]] \
          && curl -s -S --data '{"message": "'"${RESULT}"'", "title": "'"${TITLE}"'", "priority":'"${PRIORITY}"'}' \
            -X POST -H Content-Type:application/json "$URL" \
            || echo "No new versions"
          rm -f result.tmp ${{ env.LOG_FILE }}

      - name: Commit version record files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: apply version record files changes"

          branch: main
          commit_options: "--no-verify --signoff"
          file_pattern: ./*.json
          repository: .

          commit_user_name: GitHub Actions Bot
          commit_user_email: actions@github.com
          commit_author: GitHub Actions Bot <actions@github.com>
